"""add_missing_notes_columns

Revision ID: 847f6014e5b5
Revises: 1339c9cb4182
Create Date: 2026-03-31 19:21:11.958178

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '847f6014e5b5'
down_revision = '1339c9cb4182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reputation', 'usdc_earned',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('reputation', 'usdc_spent',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('reputation', 'usdc_balance',
               existing_type=mysql.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reputation', 'usdc_balance',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('reputation', 'usdc_spent',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('reputation', 'usdc_earned',
               existing_type=mysql.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
