"""add party_b_email to contracts

Revision ID: e7279267f10e
Revises: f7f5934c8991
Create Date: 2026-03-28 23:07:01.839668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7279267f10e'
down_revision = 'f7f5934c8991'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
